version: "3.10"

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      # - "6379:6379"
      - "127.0.0.1:6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      # - .env_docker
    entrypoint: ["./config/entrypoint.sh"]
    volumes:
      - .:/fastapi_app
      - ./tmp:/fastapi_app/tmp
    ports:
      # - "8000:8000"
      - "127.0.0.1:8000:8000"
    depends_on:
      - redis

  celery:
    build:
      context: .
    env_file:
      - .env
      # - .env_docker
    command: celery -A src.utils.celery_worker worker --loglevel=info
    volumes:
      - .:/fastapi_app
      - ./tmp:/fastapi_app/tmp
    depends_on:
      - redis
    environment:
      - TZ=Europe/Kyiv
  
  beat:
    build: .
    env_file:
      - .env
      # - .env_docker
    command: celery -A src.utils.celery_worker beat --loglevel=info
    volumes:
      - .:/fastapi_app
      - ./tmp:/fastapi_app/tmp
    depends_on:
      - redis
      - celery

  # db:
  #   image: postgres:17
  #   env_file:
  #     # - .env_docker
  #     - .env
  #   environment:
  #     POSTGRES_DB: ${DB_NAME}
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASS}
  #   ports:
  #     # - "5432:5432"
  #     # - "127.0.0.1:5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
