"""Content

Revision ID: bfdfaeaecf10
Revises: 28af6882d97f
Create Date: 2026-02-01 18:26:09.470758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfdfaeaecf10'
down_revision: Union[str, Sequence[str], None] = '28af6882d97f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('page', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=20), nullable=True),
    sa.Column('published_value', sa.Text(), nullable=True),
    sa.Column('draft_value', sa.Text(), nullable=True),
    sa.Column('has_unpublished_changes', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_content_id'), 'site_content', ['id'], unique=False)
    op.create_index(op.f('ix_site_content_key'), 'site_content', ['key'], unique=True)
    op.create_index(op.f('ix_site_content_page'), 'site_content', ['page'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_content_page'), table_name='site_content')
    op.drop_index(op.f('ix_site_content_key'), table_name='site_content')
    op.drop_index(op.f('ix_site_content_id'), table_name='site_content')
    op.drop_table('site_content')
    # ### end Alembic commands ###
