"""content_visibility_order

Revision ID: fd191d9c09e7
Revises: bfdfaeaecf10
Create Date: 2026-02-01 22:11:10.646360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd191d9c09e7'
down_revision: Union[str, Sequence[str], None] = 'bfdfaeaecf10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_content', sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=True))
    op.add_column('site_content', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_content', 'sort_order')
    op.drop_column('site_content', 'is_visible')
    # ### end Alembic commands ###
